#!/bin/bash
#
# utility to run dronic job
#
# put a shebang in the job file:
#	#!/usr/bin/env dronic
#
# and symlink this to a PATH'able path
#

set -e

docker pull dronic:latest

docker run --rm \
    --mount type=bind,source="$(pwd)/jobs",target=/workspace,readonly \
    dronic:latest $@

