#!/bin/bash
#
# utility to run dronic job
#
# put a shebang in the job file:
#	#!/usr/bin/env dronic
#
# and symlink this to a PATH'able path
#

set -e

test ${#@} -ge 1 || { echo "read help" ; exit 1; }

#docker pull dronic:latest

docker run --rm \
    --mount type=bind,source="$(pwd)/jobs",target=/workspace,readonly \
    --workdir /workspace \
    dronic:latest $@

